### ISSUE TITLE
Error when quering custom database

### ISSUE THREAD

**Issue by fgvieira** [J35P312/SVDB#21]
I am trying to build a custom database of SVs, and then query it to get the frequency of the SVs on a given sample. So far I have built the database:
```
svdb --build --files *.vcf.gz --prefix SVDB
```

But when I try to query it:
```
svdb --query --query_vcf sample1.vcf.gz --sqdb SVDB.db --in_occ OCC --in_frq AF --out_occ SV_AN --out_frq SV_AF
```

, I get:
```
Traceback (most recent call last):
  File "/home/projects/cu_10047/people/filipev/python2/bin/svdb", line 10, in <module>
    sys.exit(main())
  File "/home/projects/cu_10047/people/filipev/python2/lib/python2.7/site-packages/svdb/__main__.py", line 37, in main
    query_module.main(args)
  File "/home/projects/cu_10047/people/filipev/python2/lib/python2.7/site-packages/svdb/query_module.py", line 200, in main
    hits = SQDB(query,args,c)
  File "/home/projects/cu_10047/people/filipev/python2/lib/python2.7/site-packages/svdb/query_module.py", line 288, in SQDB
    ci = args.ci
AttributeError: 'Namespace' object has no attribute 'ci'
```

Any idea of what this might be?

**Comment by J35P312** [comment]
Hello!
The --sqdb query is a  bit poorly maintained, and I plan to drop it soon. I recomend exporting the sqlite database instead:

svdb --export --db SVDB.db

next, you can use  the resulting vcf as a database:

svdb --query --query_vcf sample1.vcf.gz --db SVDB.vcf > output.vcf

good luck, and sorry for the troubles!

**Comment by fgvieira** [comment]
I'll give it a try,
