### ISSUE TITLE
Error when exporting database

### ISSUE THREAD

**Issue by fgvieira** [J35P312/SVDB#23]
I am trying to export a DB into a VCF but I get an error:
```
$ svdb --export --db manta.db --overlap 0 --bnd_distance 1000 --prefix manta
Traceback (most recent call last):
  File "/services/tools/anaconda2/4.4.0/bin/svdb", line 10, in <module>
    sys.exit(main())
  File "/services/tools/anaconda2/4.4.0/lib/python2.7/site-packages/svdb/__main__.py", line 77, in main
    export_module.main(args)
  File "svdb/export_module.py", line 326, in svdb.export_module.main (svdb/export_module.c:10964)
  File "svdb/export_module.py", line 304, in svdb.export_module.export (svdb/export_module.c:10226)
  File "svdb/export_module.py", line 270, in svdb.export_module.svdb_cluster_main (svdb/export_module.c:9187)
  File "svdb/export_module.py", line 185, in svdb.export_module.overlap_cluster (svdb/export_module.c:6815)
  File "svdb/export_module.py", line 140, in svdb.export_module.expand_chain (svdb/export_module.c:5021)
UnboundLocalError: local variable 'match' referenced before assignment
```

Any idea of what it might be?

**Comment by J35P312** [comment]
Woopsiedaisy!
What version of SVDB are you running? I checked line 140 of the export_module, but here I see that match is set to true at line 140. Hence, it should not produce such error.
<img width="370" alt="Screen Shot 2019-09-03 at 15 32 37" src="https://user-images.githubusercontent.com/12830429/64177670-474e3200-ce60-11e9-8ec7-99cb72726008.png">

Maybe you have an old version of SVDB, I recommend you to clone SVDB from git hub.

I know SVDB export worked for you previosly, could it be that you have changed conda environment?

Good luck! Cloning and installing the latest version of SVDB should solve this error!

**Comment by fgvieira** [comment]
Ah yes, it seems I messed up by conda environments. :)
thanks,
