### ISSUE TITLE
Query is failing with UnicodeDecodeError

### ISSUE THREAD

**Issue by hassanfa** [J35P312/SVDB#28]
I have multiple Manta SV files and build a database already. But now with query it fails with the following error:

```
Traceback (most recent call last):
  File "xxxxx/bin/svdb", line 11, in <module>
    load_entry_point('svdb', 'console_scripts', 'svdb')()
  File "xxxx/SVDB/svdb/__main__.py", line 37, in main
    query_module.main(args)
  File "xxxxxx/SVDB/svdb/query_module.py", line 96, in main
    for line in f:
  File "xxxxxxxx/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 99: invalid continuation byte
```

Commands that I've used are:
`svdb --build --files *.vcf --prefix my_svdb`

Then followed by:
`svdb --query --db issue_49_svdb.db --query_vcf data_1.vcf`

I'm trying to run it using minimal options to test and make it work but I couldn't figure out from documentation what order or how it should be done. I tried `--export` as well, but I'm not sure how to follow it properly.

**Comment by hassanfa** [comment]
@J35P312 Thanks! So the procedure is to `--export` after build and provide `*.vcf` from the output to `--query`
