### ISSUE TITLE
main() takes exactly 2 positional arguments (1 given)

### ISSUE THREAD

**Issue by FriederikeHanssen** [J35P312/SVDB#64]
Hi,

I am trying to run the svdb module 2.7.1 with:

```
❯ svdb --query --query_vcf work/stage/e4/676eb20eb46b22b46b233c2a62a6d5/sv_query.vcf.gz  --db work/stage/e6/e425bbcf983679e5aaf6dc774c7400/gnomAD.r2.1.1-sv.vcf.gz --prefix test --in_occ AC --in_frq AF --out_occ gnomad_svAC --out_frq gnomad_svAF
```

and getting below error:

```
Traceback (most recent call last):
  File "/Users/monarchy/miniconda3/envs/svdb/bin/svdb", line 11, in <module>
    sys.exit(main())
  File "/Users/monarchy/miniconda3/envs/svdb/lib/python3.10/site-packages/svdb/__main__.py", line 93, in main
    make_query_calls(args, queries, "db")
  File "/Users/monarchy/miniconda3/envs/svdb/lib/python3.10/site-packages/svdb/__main__.py", line 40, in make_query_calls
    query_module.main(args)
  File "svdb/query_module.py", line 11, in svdb.query_module.main
TypeError: main() takes exactly 2 positional arguments (1 given)
```

I suppose, I am missing a parameter somewhere. Just for the life of me can't find which one. I have copied the test command now multiple times and filled with my files etc. If anyone has sharper eyes and could help me spot the error, I would be very grateful

**Comment by J35P312** [comment]
Hello!
Woopsiedaisy! It seems a bug was introduced in 2.7.1, I have I have fixed it now in 2.8.0.
Your command looks perfect! update (or downgrade) your SVDB, and it will work perfectly.

Good luck!
