### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by gavinmonahan** [J35P312/SVDB#69]
Hi there!

I'm using SVDB merge to combine some small cohorts of manta VCFs together, however I'm getting the following error:
```
svdb --merge --vcf b16/diploidSV.vcf.gz b15/diploidSV.vcf.gz b14/diploidSV.vcf.gz --bnd_distance 500 --overlap 0.7 > svdb_test_merge.vcf
Traceback (most recent call last):
  File "/data/conda/miniconda3/envs/svdb/bin/svdb", line 11, in <module>
    load_entry_point('svdb', 'console_scripts', 'svdb')()
  File "/data/scout/SVDB/svdb/__main__.py", line 195, in main
    merge_vcf_module.main(args)
  File "/data/scout/SVDB/svdb/merge_vcf_module.py", line 185, in main
    to_be_printed = merge_vcf_module_cython.merge(variants, samples, sample_order, sample_print_order, priority_order, args)
  File "/data/scout/SVDB/svdb/merge_vcf_module_cython.py", line 302, in merge
    samples_tag[match_id].append(collect_sample(vcf_line_B ,samples,sample_order,match_id))
  File "/data/scout/SVDB/svdb/merge_vcf_module_cython.py", line 53, in collect_sample
    sample_entries = vcf_line[9 + sample_position].split(":")
IndexError: list index out of range
```
I'm using SVDB version 2.8.2 and have tried multiple versions of python.
Any help would be greatly appreciated!
Gavin

**Comment by J35P312** [comment]
Hello!
Sorry for the delay! Interesting error, usually I get this if the vcf is either corrupted or if there is issues with the header.
Can you send the vcf files? I can take a look and see if I find the issue!

//Jesper
